/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceRouteImport } from './routes/workforce'
import { Route as SuccessionRouteImport } from './routes/succession'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ManagerEffectivenessRouteImport } from './routes/manager-effectiveness'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AttentionRouteImport } from './routes/attention'
import { Route as AtRiskRouteImport } from './routes/at-risk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuccessionDetailsRouteImport } from './routes/succession.details'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as OneOnOneSlugRouteImport } from './routes/one-on-one.$slug'
import { Route as InsightsAttritionRouteImport } from './routes/insights.attrition'
import { Route as ComplianceDetailsRouteImport } from './routes/compliance.details'

const WorkforceRoute = WorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessionRoute = SuccessionRouteImport.update({
  id: '/succession',
  path: '/succession',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerEffectivenessRoute = ManagerEffectivenessRouteImport.update({
  id: '/manager-effectiveness',
  path: '/manager-effectiveness',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AttentionRoute = AttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => rootRouteImport,
} as any)
const AtRiskRoute = AtRiskRouteImport.update({
  id: '/at-risk',
  path: '/at-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessionDetailsRoute = SuccessionDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => SuccessionRoute,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OneOnOneSlugRoute = OneOnOneSlugRouteImport.update({
  id: '/one-on-one/$slug',
  path: '/one-on-one/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsAttritionRoute = InsightsAttritionRouteImport.update({
  id: '/insights/attrition',
  path: '/insights/attrition',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceDetailsRoute = ComplianceDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => ComplianceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/attention': typeof AttentionRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/engagement': typeof EngagementRoute
  '/forecasting': typeof ForecastingRoute
  '/hiring': typeof HiringRoute
  '/learning': typeof LearningRoute
  '/manager-effectiveness': typeof ManagerEffectivenessRoute
  '/performance': typeof PerformanceRoute
  '/succession': typeof SuccessionRouteWithChildren
  '/workforce': typeof WorkforceRoute
  '/compliance/details': typeof ComplianceDetailsRoute
  '/insights/attrition': typeof InsightsAttritionRoute
  '/one-on-one/$slug': typeof OneOnOneSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/succession/details': typeof SuccessionDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/attention': typeof AttentionRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/engagement': typeof EngagementRoute
  '/forecasting': typeof ForecastingRoute
  '/hiring': typeof HiringRoute
  '/learning': typeof LearningRoute
  '/manager-effectiveness': typeof ManagerEffectivenessRoute
  '/performance': typeof PerformanceRoute
  '/succession': typeof SuccessionRouteWithChildren
  '/workforce': typeof WorkforceRoute
  '/compliance/details': typeof ComplianceDetailsRoute
  '/insights/attrition': typeof InsightsAttritionRoute
  '/one-on-one/$slug': typeof OneOnOneSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/succession/details': typeof SuccessionDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/at-risk': typeof AtRiskRoute
  '/attention': typeof AttentionRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/engagement': typeof EngagementRoute
  '/forecasting': typeof ForecastingRoute
  '/hiring': typeof HiringRoute
  '/learning': typeof LearningRoute
  '/manager-effectiveness': typeof ManagerEffectivenessRoute
  '/performance': typeof PerformanceRoute
  '/succession': typeof SuccessionRouteWithChildren
  '/workforce': typeof WorkforceRoute
  '/compliance/details': typeof ComplianceDetailsRoute
  '/insights/attrition': typeof InsightsAttritionRoute
  '/one-on-one/$slug': typeof OneOnOneSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/succession/details': typeof SuccessionDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/at-risk'
    | '/attention'
    | '/compliance'
    | '/engagement'
    | '/forecasting'
    | '/hiring'
    | '/learning'
    | '/manager-effectiveness'
    | '/performance'
    | '/succession'
    | '/workforce'
    | '/compliance/details'
    | '/insights/attrition'
    | '/one-on-one/$slug'
    | '/people/$slug'
    | '/succession/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/at-risk'
    | '/attention'
    | '/compliance'
    | '/engagement'
    | '/forecasting'
    | '/hiring'
    | '/learning'
    | '/manager-effectiveness'
    | '/performance'
    | '/succession'
    | '/workforce'
    | '/compliance/details'
    | '/insights/attrition'
    | '/one-on-one/$slug'
    | '/people/$slug'
    | '/succession/details'
  id:
    | '__root__'
    | '/'
    | '/at-risk'
    | '/attention'
    | '/compliance'
    | '/engagement'
    | '/forecasting'
    | '/hiring'
    | '/learning'
    | '/manager-effectiveness'
    | '/performance'
    | '/succession'
    | '/workforce'
    | '/compliance/details'
    | '/insights/attrition'
    | '/one-on-one/$slug'
    | '/people/$slug'
    | '/succession/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtRiskRoute: typeof AtRiskRoute
  AttentionRoute: typeof AttentionRoute
  ComplianceRoute: typeof ComplianceRouteWithChildren
  EngagementRoute: typeof EngagementRoute
  ForecastingRoute: typeof ForecastingRoute
  HiringRoute: typeof HiringRoute
  LearningRoute: typeof LearningRoute
  ManagerEffectivenessRoute: typeof ManagerEffectivenessRoute
  PerformanceRoute: typeof PerformanceRoute
  SuccessionRoute: typeof SuccessionRouteWithChildren
  WorkforceRoute: typeof WorkforceRoute
  InsightsAttritionRoute: typeof InsightsAttritionRoute
  OneOnOneSlugRoute: typeof OneOnOneSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce': {
      id: '/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof WorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succession': {
      id: '/succession'
      path: '/succession'
      fullPath: '/succession'
      preLoaderRoute: typeof SuccessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-effectiveness': {
      id: '/manager-effectiveness'
      path: '/manager-effectiveness'
      fullPath: '/manager-effectiveness'
      preLoaderRoute: typeof ManagerEffectivenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attention': {
      id: '/attention'
      path: '/attention'
      fullPath: '/attention'
      preLoaderRoute: typeof AttentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/at-risk': {
      id: '/at-risk'
      path: '/at-risk'
      fullPath: '/at-risk'
      preLoaderRoute: typeof AtRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succession/details': {
      id: '/succession/details'
      path: '/details'
      fullPath: '/succession/details'
      preLoaderRoute: typeof SuccessionDetailsRouteImport
      parentRoute: typeof SuccessionRoute
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-on-one/$slug': {
      id: '/one-on-one/$slug'
      path: '/one-on-one/$slug'
      fullPath: '/one-on-one/$slug'
      preLoaderRoute: typeof OneOnOneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/attrition': {
      id: '/insights/attrition'
      path: '/insights/attrition'
      fullPath: '/insights/attrition'
      preLoaderRoute: typeof InsightsAttritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/details': {
      id: '/compliance/details'
      path: '/details'
      fullPath: '/compliance/details'
      preLoaderRoute: typeof ComplianceDetailsRouteImport
      parentRoute: typeof ComplianceRoute
    }
  }
}

interface ComplianceRouteChildren {
  ComplianceDetailsRoute: typeof ComplianceDetailsRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  ComplianceDetailsRoute: ComplianceDetailsRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

interface SuccessionRouteChildren {
  SuccessionDetailsRoute: typeof SuccessionDetailsRoute
}

const SuccessionRouteChildren: SuccessionRouteChildren = {
  SuccessionDetailsRoute: SuccessionDetailsRoute,
}

const SuccessionRouteWithChildren = SuccessionRoute._addFileChildren(
  SuccessionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtRiskRoute: AtRiskRoute,
  AttentionRoute: AttentionRoute,
  ComplianceRoute: ComplianceRouteWithChildren,
  EngagementRoute: EngagementRoute,
  ForecastingRoute: ForecastingRoute,
  HiringRoute: HiringRoute,
  LearningRoute: LearningRoute,
  ManagerEffectivenessRoute: ManagerEffectivenessRoute,
  PerformanceRoute: PerformanceRoute,
  SuccessionRoute: SuccessionRouteWithChildren,
  WorkforceRoute: WorkforceRoute,
  InsightsAttritionRoute: InsightsAttritionRoute,
  OneOnOneSlugRoute: OneOnOneSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
